export const statNav = [
    {name: "Profile", to:"/blah/blah", icon:""},
    {name: "Export", to:"/blah/blah", icon:""},
    {name: "Import", to:"/blah/blah", icon:""},
    {name: "Trade Balance", to:"/blah/blah", icon:""},
    {name: "Monthly and Quarterly Trade Data", to:"/blah/blah", icon:""},
    {name: "Trade Indicators", to:"/blah/blah", icon:""},
    {name: "Animal", to:"/blah/blah", icon:""},
    {name: "Vegetable", to:"/blah/blah", icon:""},
    {name: "Food Products", to:"/blah/blah", icon:""},
    {name: "Minerals", to:"/blah/blah", icon:""},
    {name: "Fuels", to:"/blah/blah", icon:""},
    {name: "Chemicals", to:"/blah/blah", icon:""},
    {name: "Plastic or Rubber", to:"/blah/blah", icon:""},
    {name: "Hides and Skins", to:"/blah/blah", icon:""},
    {name: "Wood", to:"/blah/blah", icon:""},
    {name: "Textiles and Clothing", to:"/blah/blah", icon:""},
    {name: "Footwear", to:"/blah/blah", icon:""},
    {name: "Stone and Glass", to:"/blah/blah", icon:""},
    {name: "Metals", to:"/blah/blah", icon:""},
    {name: "Mach and Elec", to:"/blah/blah", icon:""},
    {name: "Transportation", to:"/blah/blah", icon:""},
    {name: "Miscellaneous", to:"/blah/blah", icon:""},
    {name: "All Products", to:"/blah/blah", icon:""}
]